image: gitlab.devartis.com:4567/devops/devops:latest

stages:
  - build
  - test
#  - deploy

variables:
  PIP_CACHE_DIR: ./.pip-cache
  PYTHON_VENV_DIR: ./.env
  DJANGO_SETTINGS_MODULE: project_name.settings.testing
  PYTHON_SCRIPT: python3

build:
  stage: build
  cache:
    paths:
      - $PIP_CACHE_DIR
      - $PYTHON_VENV_DIR
  artifacts:
    paths:
      - $PIP_CACHE_DIR
      - $PYTHON_VENV_DIR
  script:
    - $PYTHON_SCRIPT -m venv $PYTHON_ENV_DIR
    - source $PYTHON_ENV_DIR/bin/activate
    - pip install -r requirements/testing.txt --cache-dir $PIP_CACHE_DIR

.test_template: &test_definition
  stage: test
  before_script:
    - source $PYTHON_ENV_DIR/bin/activate
  dependencies:
    - build

pylint:
  <<: *test_definition
  script:
    - $PYTHON_SCRIPT -m pylint -f parseable project_name --rcfile=.pylintrc

migration_test:
  <<: *test_definition
  script:
    - $PYTHON_SCRIPT manage.py migrate --settings=$DJANGO_SETTINGS_MODULE

django_tests:
  <<: *test_definition
  script:
    - $PYTHON_SCRIPT manage.py test --stop --with-coverage --cover-branches  --cover-inclusive --cover-package=project_name --settings=project_name.settings.testing --exclude=settings --exclude=migrations

pep8:
  image: gitlab.devartis.com:4567/devops/devops:pep8
  stage: test
  script: pep8 project_name --max-line-length=140 --ignore=E731 --exclude=**/migrations/,__init__.py

jscpd:
  image: gitlab.devartis.com:4567/devops/devops:jscpd
  stage: test
  script: jscpd --verbose --o /dev/null --limit 1
